services:
  backend:
    image: backend:dev
    container_name: backend-dev
    build:
      context: .
      dockerfile: Dockerfile #docker init產生的完整版文件
      target: deps #要挑階段給docker當image
    working_dir: /build #對應Dockerfile的WORKDIR
    command: ["./mvnw", "spring-boot:run"]
    ports:
      - "8083:8082"
    volumes:
      - .:/build #整個專案掛進去build
      - ./uploads:/app/uploads
      - m2_cache:/root/.m2

volumes:
  m2_cache: