server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # nginx要fallback使用的router檔案
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API proxy（如果需要）
    # location /api/ {
    #     proxy_pass http://backend:8082/;
    # }
}
